// Auto-generated by scripts/fetch-channel-icons.py
window.CHANNEL_ICONS = {
  "Half-Asleep Chris": "https://yt3.googleusercontent.com/ytc/AIdro_kqEIIIyK7JWnLZOyJO6Zx2fomJMPoQJpxtlVOgg3jA3p0=s900-c-k-c0x00ffffff-no-rj",
  "Lofi Girl": "https://yt3.googleusercontent.com/_BSh2VVvVMzqBoKyWbQnyC35XFOV-ZbXavf9nfu3ZjpFUGEImQnlWt9ZlpfGQBqWEbGNc4rPWg=s900-c-k-c0x00ffffff-no-rj",
  "Mark Rober": "https://yt3.googleusercontent.com/ytc/AIdro_ksXY2REjZ6gYKSgnWT5jC_zT9mX900vyFtVinR8KbHww=s900-c-k-c0x00ffffff-no-rj",
  "Odd Animal Specimens": "https://yt3.googleusercontent.com/cBPSSE416_IJVaHINNZWKl08GPZK3TInvrpS7Or446P6kzrqcAUps5AipcXvzsf2ImJndv7O9w=s900-c-k-c0x00ffffff-no-rj",
  "RedLetterMedia": "https://yt3.googleusercontent.com/ytc/AIdro_n98yLJDWtiZyJmgHBIRSYsA7qgDMJJdAHs4Zs-tgMI8iQ=s900-c-k-c0x00ffffff-no-rj",
  "Sportsnet": "https://yt3.googleusercontent.com/ytc/AIdro_lhlHXzqaG5uUBTU0OaM53lnRcb94wt34nf_m9kIElWBOk=s900-c-k-c0x00ffffff-no-rj",
  "TerraGreen1": "https://yt3.googleusercontent.com/wM1wPhLHjeNgDA1eJFvinz6sP9tR_miBnSVnzwmJuVykagPi677ZUXOwnPctiK1ZM6itMOtMpNY=s900-c-k-c0x00ffffff-no-rj",
  "WolfeyVGC": "https://yt3.googleusercontent.com/og8-k9sj6tzQR_6ze8iWjtPrE7uIqu7tzNhEAC1UKvlggs8FzvVPr3p3vBmGvbrym9zDdOkL=s900-c-k-c0x00ffffff-no-rj",
};
