// Edit this list to add or remove videos.
// id = the value after v= in the YouTube URL
window.VIDEO_LIST = [
  { id: "jfKfPfyJRdk", title: "lofi hip hop radio - beats to relax/study to" },
  { id: "DWcJFNfaw9c", title: "lofi hip hop radio - beats to sleep/chill to" },
  { id: "5qap5aO4i9A", title: "lofi hip hop radio - beats to study/relax to" },
  { id: "Ai3L_iwn5oE", title: "I Entered a Tournament with a New Mega Pokemon" },
  { id: "Ip7oe0vswH0", title: "Mystery Men - re:Visit" },
  { id: "UcBH6MCAst8", title: "What Are Next for Star Trek?" },
  { id: "y1cbgJX0_Mo", title: "Ralph's been seriously ill (but is now fine!)" },
  { id: "oE7t8MYRgbI", title: "I Built LEGO Concorde ON Concorde!" },
  { id: "OUgDwUz4_fI", title: "Cat MYSTERY Boxes..." },
  { id: "eQrTFEFbGv8", title: "Incredible Cat Tech" },
  { id: "q2tXdlohlYI", title: "Terrible Cat Puns" },
  { id: "NVLDqaSJN4o", title: "I Made 100 GIANT LEGO-style Pieces" },
  { id: "8Q_sebGRkAM", title: "I Built A Cat-Feeding Contraption!" },
  { id: "8ngjz9RUoYw", title: "The Most Ridiculously British Invention of All Time" },
  { id: "NwUHZZDFBDA", title: "I Gave My Cats The Best Day Ever!" },
  { id: "KEeLJ13VuUc", title: "Testing Crazy Cat Toys & Gadgets" },
  { id: "38cRj-mDq2s", title: "Art Attack - When Masterpieces Get Vandalised" },
  { id: "VxSGrFSQS1I", title: "Incredible Cat Tunnels" },
  { id: "DLWOTc6F4sQ", title: "I Turned My Cat Into LEGO!" },
  { id: "esHPkO8XAOQ", title: "I Built A CAT POOP Cleaning Contraption!" },
  { id: "mv5qSZY_jPU", title: "I Built Cat WALKWAYS Around My House!" },
  { id: "fNpcdEPkx0Q", title: "Reggie Hasnât Been Well" },
  { id: "7rzyGHN5_1s", title: "I IQ Tested My Cats" },
  { id: "QTk8Lx_Lpsk", title: "I Put a Tiny Camera on My Cat for 24 Hours #AD" },
  { id: "G-d2bkcPEb4", title: "I Built a LEGO Train Around My CEILING!" },
  { id: "qeICIIIAxB4", title: "Single-Use Plastic - Explained in Stop-Motion" },
  { id: "5uHwzJuLSHg", title: "I Built The Golden Gate Bridge For My Cat" },
  { id: "a5YXBwc7fAg", title: "What My CATS Do At NIGHT..." },
  { id: "5W0nJCA4e3M", title: "I Built A TREEHOUSE For My Cats! (NEW Catio)" },
  { id: "Ibk0O7JfIkE", title: "I Built MY HOUSE Out Of LEGO" },
  { id: "_EuvMVhb9Dk", title: "Remembering Bella" },
  { id: "LzQ8KHlEOMo", title: "Cats Vs. Dominoes!" },
  { id: "QxyLJ8Ao93I", title: "Testing Crazy Catnip Products!" },
  { id: "QBEt7zKJIEI", title: "Updating the Cats' Theme Song" },
  { id: "q-0BBc-hNNQ", title: "Extreme LEGO Colour CHALLENGE!" },
  { id: "HUhcCQqXCRU", title: "I Made a Keyboard From My Cat's Meows" },
  { id: "-q7U5WK6DBc", title: "Testing WEIRD CAT Products" },
  { id: "n5ByVudZ-Es", title: "I Built 10 Incredible Cat Forts!" },
  { id: "Q87CwzuhPGU", title: "I Built a LEGO RACETRACK Around My House!" },
  { id: "YtYc-RLInrU", title: "I Built a LEGO Breakfast Train! (Rube Goldberg Machine)" },
  { id: "rBlT6CA_vYY", title: "I Built A CASTLE For My KITTEN!" },
  { id: "8OM6a_JieaM", title: "I Picked Up A TON of Trash (Literally!)" },
  { id: "BRwff01zkFU", title: "Kittens & Counterweights" },
  { id: "hW7IxG-EUNw", title: "Bella 2009-2026" },
  { id: "lFtR6NWEFA4", title: "Bringing the Dinosaurs Back to Life" },
  { id: "cPbKsX8uzUI", title: "I Built the Ultimate RC Car Obstacle Course" },
  { id: "UPp3v8ScLnc", title: "The Queen's Noisy Neighbours" },
  { id: "KQqMUjMlKGo", title: "I Built a GIANT LEGO Castleâ¦" },
  { id: "a7kz7oJtlqE", title: "I LEGALLY Made My Cats LORD & LADY!" },
  { id: "lo_svJo9XkA", title: "Giant Cat Destroys LEGO City" },
  { id: "EldMeRSdqtc", title: "Kitten Vs. Robots!" },
  { id: "P675aYfce4M", title: "Working LEGO Rollercoaster IN SPACE!" },
  { id: "t7fGPE7M6MU", title: "I Built a HUGE Lego Rollercoaster - Floor to Ceiling!" },
  { id: "clEkEWpo1I0", title: "The Loch Ness Tragedy" },
  { id: "ol4cSs95L0Q", title: "I Opened a GOURMET Restaurant For FOXES!" },
  { id: "EG3H5VV1LAI", title: "I Got A KITTEN!" },
  { id: "BgW0Lk3Dlc0", title: "I Used ROBOTS To Look After My Cats" },
  { id: "LbA9xcsTK94", title: "100,000 Piece LEGO Art Challenge!" },
  { id: "fukUKeCDdro", title: "Incredible CAT Illusions!" },
  { id: "ECn2al0M98s", title: "I Built a HUGE Lego Railway - Up Stairs & Underwater!" },
  { id: "fFmHhotdVQU", title: "I Built a Theme Park BOAT RIDE In My Garden!" },
  { id: "PhNFaSnYhy4", title: "Recreating Cat Memes - Money Cat, Bread Cat & Chemistry Cat" },
  { id: "3a6t7X2ftoA", title: "Can We Build a Giant LEGO Festive Train Track?  | Half-Asleep Chris | LEGO" },
  { id: "KfCRXrFBKDM", title: "I Built 100 FREE LEGO Sets!" },
  { id: "GBN0Y9sA6W8", title: "Extreme CAT Hide And Seek - Challenge" },
  { id: "b0_d-VuAQvw", title: "Ralph & Bella Meet For The First Time" },
  { id: "Eeo05dgKj8k", title: "I Made a Colouring Book!" },
  { id: "hzWd94btPRc", title: "I Wrote A Theme Song For My Cats" },
  { id: "wPMuG8sMlLA", title: "My Cat's Secret OTHER LIFE" },
  { id: "oBd66P1MTOI", title: "Kitten Destroys LEGO Village!" },
  { id: "tLXaWg64kmY", title: "I Threw My CATS a CHRISTMAS Party!" },
  { id: "v8sFhkV_gN0", title: "I Built A TUNNEL NETWORK For My Cats" },
  { id: "bnf9LxUtxV8", title: "Half-asleep Chris Meets Boop" },
  { id: "SKGldCd-i3Y", title: "I Built a LEGO City From Scratch!" },
  { id: "haGOX7TMT0M", title: "I Built A GIGANTIC Cat Fort For My Cats" },
  { id: "PHaGGkIKEQE", title: "Me & Bella are in a LEGO Film!" },
  { id: "6Q94SgThC9I", title: "Cats in Squares" },
  { id: "09hAl2fIt8A", title: "Ralph Vs. Bella - GIANT Cat Maze" },
  { id: "PsKN3DWijpo", title: "The To-Do List" },
  { id: "7WTPojnwfQM", title: "I 3D Printed My Cats!" },
  { id: "8NR62Em3Gck", title: "The Secret Spider on the $1 Bill" },
  { id: "rB3gJmeQ4bs", title: "I Built a GIANT LEGO City! (Neighbourhood)" },
  { id: "N2iSUlLD374", title: "100 Trillion Dollars - A Worthless Banknote?!" },
  { id: "Opy92oP2HSw", title: "A 60-Second Action Movie" },
  { id: "G3NvcFKeemo", title: "PUPPY Rides a LEGO Train!" },
  { id: "kk5AaZVVwrE", title: "I Took a Royal PAW-trait of my Cat" },
  { id: "uTHsx_wVL5M", title: "I Built The TALLEST LEGO SETS Ever Released!" },
  { id: "qwIzroS0Lfo", title: "I Made My Cat Out of Lego (Life-sized!)" },
  { id: "zPAtSGhxwHc", title: "I Built The BIGGEST LEGO SETS Ever Released!" },
  { id: "VAuUtv4um4Q", title: "The Music Box Project" },
  { id: "gRPC_Z484EA", title: "I Filmed Baby Foxes With Hidden Cameras" },
  { id: "rMUlkAamb2c", title: "Secrets & Easter Eggs of Disneyland Paris" },
  { id: "zzIGH4x5LME", title: "The Worldâs Coolest Building" },
  { id: "9BK_4cm1mJI", title: "I Built a LEGO Underground Railway!" },
  { id: "KtaCycCKmo0", title: "The Great New Zealand Road Trip" },
  { id: "9EMJtotXQ6Q", title: "Monkey Vs. LEGO!" },
  { id: "wsu-jDcONxk", title: "A Not-So-English Breakfast" },
  { id: "OBLg3i6h7Kk", title: "I Attempted Extreme LEGO Challenges!" },
  { id: "aPkIv2OXVRg", title: "The Supermarket Tunnel That Became A World Wonder" },
  { id: "LhmUw1uF-WQ", title: "I Built 100 LEGO Buildings!" },
  { id: "_ZCfVz6K8Cc", title: "How To Make Your Own Zoetrope" },
  { id: "RuP5Y7k1K7o", title: "A Mildly Interesting Door" },
  { id: "7pMibzPor9k", title: "I Built ITALY Out Of LEGO! (In Italy!)" },
  { id: "OeUaRJKO7BI", title: "I Built an ADVENTURE PLAYGROUND CATIO For My Cats" },
  { id: "TXI8g49xtsA", title: "I Got The World's Largest Pets!" },
  { id: "57AQNt_WowE", title: "I Got a Pet Dragon... (actually flies)" },
  { id: "tZMq9lhS7sQ", title: "My Best Pets of 2026 (so far)" },
  { id: "uyPJC8i6sTw", title: "1,000 Ants vs. Challenges" },
  { id: "ES3jHxrt0mI", title: "I Got a Pet Alien Worm... (spits slime)" },
  { id: "VWAxZQE0mjo", title: "I Flipped 100 Rocks in an Exotic Jungle, Here's What I Found..." },
  { id: "zkCP__V3RkU", title: "$1 vs. $100,000 Pet Fish!" },
  { id: "hXlHnrv_dYg", title: "1,000 Termites vs. House" },
  { id: "lkg8vXS9u1k", title: "I Flipped 100 Rocks in Australia, Here's What I Found..." },
  { id: "mLZ8AzaJjQs", title: "$1 vs. $100,000 Pet Snake!" },
  { id: "x1O5HNNyFTY", title: "1,000 Ants vs. Natural Disasters" },
  { id: "Lc1wyZk55vo", title: "1,000 Mosquitoes vs. Blood" },
  { id: "HgXTy_QyPGY", title: "10,000 Mealworms vs. Watermelon" },
  { id: "bgN5OqLzfBo", title: "1,000 Ants vs. Obstacles" },
  { id: "9YYx1tokxIY", title: "the craziest animal videos i've ever seen" },
  { id: "2V4JtZwq2_E", title: "Get STUNG By Cow Killer, Win $10,000" },
  { id: "hLQa8PlPr-k", title: "1,000 Flies vs. Venus Fly Trap" },
  { id: "Vml5S5YY3t0", title: "The Craziest Insect Videos On The Internet!" },
  { id: "SOZN4sZk7Oc", title: "Deadliest Insects vs. Finger" },
  { id: "xzqJmAg30Cw", title: "My Best Animal Videos of 2025!" },
  { id: "qSskpaHiEic", title: "How Much Weight Can a Spider Web Hold?" },
  { id: "mLG4jj2vv-k", title: "I Got a Pet Toe-Biter (will bite your toes)" },
  { id: "QtfFXg2V8gI", title: "I Saved an Abandoned Axolotl..." },
  { id: "EeA_qxly9B0", title: "1,000 Ants vs. Black Widow" },
  { id: "qyPlSWGA8us", title: "I Flipped 100 Rocks at Night, Here’s What I Found..." },
  { id: "hq8SeQHjqgY", title: "I Built a Mega Fish Tank (for the coolest fish)" },
  { id: "RWY9IJHqJOA", title: "Black Widow vs. Venus Fly Trap" },
  { id: "SJYQNRNzVkI", title: "I Flipped 100 Rocks in a Rainforest, Here's What I Found..." },
  { id: "Tsqw78IgEmA", title: "My Craziest Pets of 2025!" },
  { id: "SnRKrMM2Afg", title: "I Got a Pet Bloodworm (yes, really)" },
  { id: "kAD7BtwCbZA", title: "I Flipped 100 Rocks, Here's What I Found..." },
  { id: "rGijZUyPquA", title: "This Bug Pretends To Be a Flower To Hunt..." },
  { id: "HZtbD074LUY", title: "Simulating an Ant Colony For 100 Days" },
  { id: "42GzKkPQAoc", title: "I Got a Pet Black Widow (yes, really)" },
  { id: "ns5wpAYUwss", title: "I Transformed an Abandoned Turtle’s Home" },
  { id: "ePMMxckazYI", title: "I Got Pet Piranhas... (yes, really)" },
  { id: "mmzy05r9ZE0", title: "I Got a Pet 2-Headed Snake... (0.001%)" },
  { id: "JzO7F07ah4s", title: "I Transformed an Abandoned Snake’s Home" },
  { id: "K8bk9JSx1nU", title: "I Got a Pet Cow Killer (most painful sting)" },
  { id: "dXyI9mOVGQo", title: "I Got Pet Bed Bugs (and fed them...)" },
  { id: "9efIjNvUhD4", title: "My Best Pets of 2024" },
  { id: "88LSlmp7DzE", title: "I Transformed an Abandoned Axolotl’s Home" },
  { id: "alJ1KJu5h9U", title: "I Got a Pet Leech (yes, really)" },
  { id: "z58hvdyLiyE", title: "I Got The 7 Weirdest Pet Fish..." },
  { id: "_LXcZWs1gpE", title: "Raising Tadpoles into Frogs (50 Day Evolution)" },
  { id: "Jqj0qz6dAcw", title: "I Got a Pet Alien (kinda)" },
  { id: "0Ecfy5e4U3Y", title: "I Got The Rarest Pet Lizard" },
  { id: "QLI0XOFpK0A", title: "I Got a Pet Dinosaur (kinda)" },
  { id: "tJmVwualgV8", title: "Transforming an Abandoned Aquarium (with fish)" },
  { id: "OKIs9TUY-94", title: "I Got The Largest Pet Spider (yes, really)" },
  { id: "z4S4RAise6o", title: "I Got a Pet Walking Fish (literally)" },
  { id: "P2hU_ThvYwM", title: "I Built Homes For Exotic Insects..." },
  { id: "bRH3c9RfXtA", title: "$10 vs $1,000 Terrarium Ecosystem!" },
  { id: "hAtF3Jhb5VQ", title: "Simulating an Ant Colony For 30 Days" },
  { id: "IfBTM60dBeI", title: "I Built a Rainforest For My Pet Scorpion" },
  { id: "cMNpepE176s", title: "I Built a Lake Ecosystem on My Desk" },
  { id: "-yY1tmd2E_I", title: "Simulating a Beach for 30 Days" },
  { id: "Lwkmsh0AKx8", title: "Simulating a Rainforest for 30 Days" },
];
