#!/usr/bin/env python3
"""Generate channel-icons.js from YouTube channel pages."""

from __future__ import annotations

import json
import re
import subprocess
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHANNELS_JS = ROOT / "channels.js"
OUT_JS = ROOT / "channel-icons.js"

STATIC_CHANNELS = {
    "Lofi Girl": "@LofiGirl",
    "WolfeyVGC": "@WolfeyVGC",
    "RedLetterMedia": "@RedLetterMedia",
    "Half-Asleep Chris": "@HalfAsleepChris",
    "TerraGreen1": "@TerraGreen1",
    "Goosebumps": None,
    "Care Bears": None,
}


def js_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def load_dynamic_channels() -> list[dict]:
    text = CHANNELS_JS.read_text(encoding="utf-8")
    channels = []
    for block in re.findall(r"\{[^{}]+\}", text, re.S):
        channel_id = re.search(r'channelId:\s*"([^"]+)"', block)
        channel = re.search(r'channel:\s*"([^"]+)"', block)
        handle = re.search(r'handle:\s*"([^"]+)"', block)
        if channel_id and channel:
            channels.append(
                {
                    "channel": channel.group(1),
                    "channelId": channel_id.group(1),
                    "handle": handle.group(1) if handle else None,
                }
            )
    return channels


def fetch_avatar_from_page(handle: str) -> str | None:
    url = f"https://www.youtube.com/@{handle.lstrip('@')}"
    request = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(request, timeout=30) as response:
        html = response.read().decode("utf-8", "replace")

    patterns = [
        r'"avatar":\{"thumbnails":\[\{"url":"([^"]+)"',
        r'"channelAvatarRenderer"[\s\S]{0,800}?"url":"(https://yt3[^"]+)"',
    ]
    for pattern in patterns:
        match = re.search(pattern, html)
        if match:
            return match.group(1)
    return None


def fetch_avatar_from_video(handle: str) -> str | None:
    proc = subprocess.run(
        [
            "python",
            "-m",
            "yt_dlp",
            "-j",
            "--playlist-end",
            "1",
            f"https://www.youtube.com/@{handle.lstrip('@')}/videos",
        ],
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    if proc.returncode != 0:
        return None

    data = json.loads(proc.stdout.strip().splitlines()[0])
    channel_id = data.get("channel_id")
    if not channel_id:
        return None

    return f"https://www.youtube.com/s/desktop/{channel_id}/avatar/default.jpg"


def resolve_icon(channel_name: str, handle: str | None, channel_id: str | None) -> str | None:
    if handle:
        icon = fetch_avatar_from_page(handle)
        if icon:
            return icon
        icon = fetch_avatar_from_video(handle)
        if icon:
            return icon

    if channel_id:
        return f"https://www.youtube.com/s/desktop/{channel_id}/avatar/default.jpg"

    return None


def main() -> None:
    icons: dict[str, str] = {}

    for channel in load_dynamic_channels():
        icon = resolve_icon(channel["channel"], channel.get("handle"), channel["channelId"])
        if icon:
            icons[channel["channel"]] = icon
            print(f"OK {channel['channel']}")
        else:
            print(f"MISSING {channel['channel']}")

    for channel_name, handle in STATIC_CHANNELS.items():
        if channel_name in icons:
            continue
        try:
            icon = resolve_icon(channel_name, handle, None)
        except Exception as error:
            print(f"MISSING {channel_name}: {error}")
            icon = None
        if icon:
            icons[channel_name] = icon
            print(f"OK {channel_name}")
        else:
            print(f"MISSING {channel_name}")

    lines = [
        "// Auto-generated by scripts/fetch-channel-icons.py",
        "window.CHANNEL_ICONS = {",
    ]
    for channel, icon in sorted(icons.items()):
        lines.append(f'  "{js_string(channel)}": "{js_string(icon)}",')
    lines.append("};")
    lines.append("")
    OUT_JS.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(icons)} icons to {OUT_JS}")


if __name__ == "__main__":
    main()
