#!/usr/bin/env python3
"""Refresh dynamic-videos.js from YouTube RSS feeds and recent uploads."""

from __future__ import annotations

import json
import re
import subprocess
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHANNELS_JS = ROOT / "channels.js"
OUT_JS = ROOT / "dynamic-videos.js"
RECENT_UPLOADS = 50
SHORT_MAX_SECONDS = 60


def load_channels_config() -> list[dict]:
    text = CHANNELS_JS.read_text(encoding="utf-8")
    channels = []
    for block in re.findall(r"\{[^{}]+\}", text, re.S):
        channel_id = re.search(r'channelId:\s*"([^"]+)"', block)
        channel = re.search(r'channel:\s*"([^"]+)"', block)
        handle = re.search(r'handle:\s*"([^"]+)"', block)
        tags = re.findall(r'"([^"]+)"', re.search(r"tags:\s*\[(.*?)\]", block, re.S).group(1)) if re.search(r"tags:\s*\[", block) else []
        if channel_id and channel:
            channels.append(
                {
                    "channelId": channel_id.group(1),
                    "channel": channel.group(1),
                    "handle": handle.group(1) if handle else None,
                    "tags": tags,
                }
            )
    return channels


def fetch_rss(channel_id: str) -> list[dict]:
    url = f"https://www.youtube.com/feeds/videos.xml?channel_id={channel_id}"
    request = urllib.request.Request(url, headers={"User-Agent": "VideoLounge/1.0"})
    with urllib.request.urlopen(request, timeout=30) as response:
        root = ET.fromstring(response.read())

    ns = {
        "atom": "http://www.w3.org/2005/Atom",
        "yt": "http://www.youtube.com/xml/schemas/2015",
    }
    videos = []
    for entry in root.findall("atom:entry", ns):
        video_id = entry.find("yt:videoId", ns)
        title = entry.find("atom:title", ns)
        if video_id is None or title is None:
            continue
        videos.append({"id": video_id.text, "title": title.text})
    return filter_out_shorts(videos)


def is_long_form_video(video_id: str) -> bool:
    proc = subprocess.run(
        [
            "python",
            "-m",
            "yt_dlp",
            "--match-filter",
            f"duration > {SHORT_MAX_SECONDS}",
            "--print",
            "id",
            f"https://www.youtube.com/watch?v={video_id}",
        ],
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    return proc.returncode == 0 and proc.stdout.strip() == video_id


def filter_out_shorts(videos: list[dict]) -> list[dict]:
    kept = []
    for video in videos:
        if is_long_form_video(video["id"]):
            kept.append(video)
    return kept


def fetch_recent_uploads(handle: str, limit: int) -> list[dict]:
    proc = subprocess.run(
        [
            "python",
            "-m",
            "yt_dlp",
            "--flat-playlist",
            f"--playlist-end={limit}",
            "--print",
            "%(id)s|%(title)s",
            f"https://www.youtube.com/@{handle.lstrip('@')}/videos",
        ],
        capture_output=True,
        text=True,
        timeout=180,
        check=False,
    )
    videos = []
    for line in proc.stdout.splitlines():
        if "|" not in line:
            continue
        vid, title = line.split("|", 1)
        if vid == "NA":
            continue
        videos.append({"id": vid, "title": title})
    return filter_out_shorts(videos)


def js_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    channels = load_channels_config()
    merged: dict[str, dict] = {}

    for channel in channels:
        channel_name = channel["channel"]
        channel_id = channel["channelId"]
        tags = channel["tags"]

        sources = [fetch_rss(channel_id)]
        if channel.get("handle"):
            sources.append(fetch_recent_uploads(channel["handle"], RECENT_UPLOADS))

        for source in sources:
            for video in source:
                merged[video["id"]] = {
                    "id": video["id"],
                    "title": video["title"],
                    "channel": channel_name,
                    "tags": tags,
                }

    lines = [
        "// Auto-generated by scripts/sync-dynamic-channels.py",
        "// These channels also refresh in the browser when deployed with Netlify.",
        "window.DYNAMIC_VIDEO_LIST = [",
    ]
    for video in merged.values():
        tag_text = ", ".join(f'"{js_string(tag)}"' for tag in video["tags"])
        lines.append(
            f'  {{ id: "{video["id"]}", title: "{js_string(video["title"])}", '
            f'channel: "{js_string(video["channel"])}", tags: [{tag_text}] }},'
        )
    lines.append("];")
    lines.append("")
    OUT_JS.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(merged)} dynamic videos to {OUT_JS}")


if __name__ == "__main__":
    main()
